//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1905ct0020_LHT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_danhmuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_danhmuc()
        {
            this.tbl_baiviet = new HashSet<tbl_baiviet>();
        }
    
        public int id_danhmuc { get; set; }
        public string tendanhmuc { get; set; }
        public Nullable<int> thutu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_baiviet> tbl_baiviet { get; set; }
    }
}
