//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1905ct0020_LHT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin
    {
        public int id_admin { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int admin_status { get; set; }
    }
}
